# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'manufacturers',
                'verbose_name': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='media/pedals')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedals.Manufacturer')),
            ],
            options={
                'verbose_name_plural': 'pedals',
                'verbose_name': 'pedal',
            },
        ),
        migrations.CreateModel(
            name='PedalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'pedal types',
                'verbose_name': 'pedal type',
            },
        ),
        migrations.AddField(
            model_name='pedal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedals.PedalType'),
        ),
    ]
